name: fov_fall2024_headchef_tablet_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  convex_bottom_bar: ^3.2.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  signalr_netcore: ^1.4.0
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
